### Scientific Python

In [1]:
x = [1, 2, 3]
y = [4, 9, 16]
print(x+y)

[1, 2, 3, 4, 9, 16]


### Numpy

In [3]:
import numpy

In [4]:
x_numpy = numpy.array(x)
y_numpy = numpy.array(y)
print(x_numpy + y_numpy)
print(x_numpy[0])
print(y_numpy[1:])

[ 5 11 19]
1
[ 9 16]


In [5]:
print(3*x_numpy)
print(numpy.log(x_numpy))
print(x_numpy*y_numpy)
print((x_numpy-1)**2)

[3 6 9]
[0.         0.69314718 1.09861229]
[ 4 18 48]
[0 1 4]


In [6]:
A_numpy = numpy.array([ [1, 2, 3], [4, 5, 6], [7, 8, 0]])
print(A_numpy**2)

[[ 1  4  9]
 [16 25 36]
 [49 64  0]]


In [8]:
x_squared = numpy.dot(x_numpy, x_numpy)
A_times_x = numpy.dot(A_numpy, x_numpy)
print(x_squared)
print(A_times_x)

14
[14 32 23]


In [7]:
print(x_numpy.size)
print(x_numpy.shape)
print(A_numpy.size)
print(A_numpy.shape)

3
(3,)
9
(3, 3)


#### Linear Algebra

In [9]:
from scipy import linalg

In [10]:
print(linalg.solve(A_numpy, x_numpy))
print(linalg.det(A_numpy))

[-3.33333333e-01  6.66666667e-01 -3.52451754e-18]
27.0


#### Working with files

In [14]:
numpy.savetxt('data/A_numpy.txt', A_numpy)

In [15]:
!cat A_numpy.txt

'cat' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.


In [16]:
A_from_file = numpy.loadtxt('data/A_numpy.txt')
print(A_from_file == A_numpy)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Plotting

### Scipy

### Exercise: Lorenz attractor

### Exercise: Mandelbrot

### Exercise: The shortest published Mathematical paper

### End.